### ISSUE TITLE
console warning of zustand

### ISSUE THREAD

**Issue by msyesyan** [TexteaInc/json-viewer#230] opened 2023-02-11 01:38 UTC
<img width="795" alt="Screen Shot 2023-02-11 at 09 29 14" src="https://user-images.githubusercontent.com/2162116/218231534-8ae5df8e-38f4-4bef-9c0b-711b89a32803.png">

<img width="1532" alt="Screen Shot 2023-02-11 at 09 38 03" src="https://user-images.githubusercontent.com/2162116/218231839-7f66f1ad-adae-4b81-a726-07d1e75a6418.png">

The json-viewer is amazing however it will console a lot of warning message because of some deprecated usage of zustand. these console warning message give me some trouble, do you have a plan to check and replace these deprecated methods and release a new npm version? thanks

**Comment by pionxzh** [comment] 2023-02-11 03:18
Yes. We are considering moving to React context or another state-management solution. Or maybe just migrate the deprecated part 😄

**Comment by pionxzh** [comment] 2023-02-11 03:19
Duplicate of #144

**Closed** 2023-02-11 03:19 UTC
Labels: duplicate
